### ISSUE TITLE
Arch install cp to wrong folder in Makefile

### ISSUE THREAD

**Issue by fawqsir** [BeardOverflow/msi-ec#1]
I am using Garuda Linux (Arch based) on a MSI GL65 9SE
I had an error when running ``make install`` where it could not find the msi-ec.ko at line 15.

I forgot to copy the error for reporting.

I changed the Makefile line 12 to 
```
cp msi-ec.ko /lib/modules/$(shell uname -r)/
```

All is working fantastic! I haven't checked all of the stats but the fans instantaneously changed.

**Comment by fawqsir** [comment]
just a little feed back. Don't get me wrong this is awesome.

~~~
cat /sys/devices/platform/msi-ec/webcam
File: /sys/devices/platform/msi-ec/webcam
unknown (75)

cat /sys/devices/platform/msi-ec/fn_key
File: /sys/devices/platform/msi-ec/fn_key
unknown (0)

cat /sys/devices/platform/msi-ec/win_key
File: /sys/devices/platform/msi-ec/win_key
unknown (0)

This one could be because I edited the values in the kde settings to 90% max charge at 50%
cat /sys/devices/platform/msi-ec/battery_mode
File: /sys/devices/platform/msi-ec/battery_mode
unknown (218)

cat /sys/devices/platform/msi-ec/fan_mode
File: /sys/devices/platform/msi-ec/fan_mode
unknown (12)

cat /sys/devices/platform/msi-ec/fw_version
File: /sys/devices/platform/msi-ec/fw_version
16U5EMS1.100

cat /sys/devices/platform/msi-ec/fw_release_date
File: /sys/devices/platform/msi-ec/fw_release_date
2019/06/25 10:24:07

The rest is all working like it should. Super impressed.

**Comment by BeardOverflow** [comment]
According to the [kernel module's guide](https://docs.kernel.org/kbuild/modules.html#module-installation):

> Modules which are included in the kernel are installed in the directory:
>    /lib/modules/$(KERNELRELEASE)/kernel/
>
> And external modules are installed in:
>    /lib/modules/$(KERNELRELEASE)/extra/

Therefore, the true path has to be `/lib/modules/$(KERNELRELEASE)/extra`.
After clarifying that point, the `/extra` folder seems not to exist sometimes, so I did a new commit in order to prepare the folder previously. I know that `module_install` already does it, but I prefer doing all the steps manually.

Also, don't use the same issue for two questions. I have separate the second comment to a new issue #2
