### ISSUE TITLE
MSI Summit E16 Flip (A12UCT model) 

### ISSUE THREAD

**Issue by rottenpants466** [BeardOverflow/msi-ec#6]
Hi, linux newbie here, trying to ditch windows for good. Im wondering if my laptop is supported and how i can contribute to this repository.

Thank you for creating this, one of the things i really miss from control center is being able to limit the battery charge.

**Comment by BeardOverflow** [comment]
Actually, I am working to support more models, but I don't know if your model is already supported.

You can contribute using your laptop to test each entry in [the msi-ec's platform device](https://github.com/BeardOverflow/msi-ec#usage). Initially, **do it as read-only**. For example, whether the webcam is enabled or disabled: `cat /sys/devices/platform/msi-ec/webcam`. If you can read the param and looks good, then you could write it too. Otherwise, a decimal value is given instead. Post here the wrong values or unsupported entries.

Also, you may attach in this issue which is the output for the `dmidecode` command in order to identify your laptop model in the future.

**Comment by rottenpants466** [comment]
Thanks for the reply :)

Here's what you requested. I don't know if this is useful.

I'm running kubuntu 22.04 on this laptop. Wifi is not working but i think it's because of the kernel version.

[devices.txt](https://github.com/BeardOverflow/msi-ec/files/9747476/devices.txt)
[dmidecode.txt](https://github.com/BeardOverflow/msi-ec/files/9747477/dmidecode.txt)

cheers

**Comment by rottenpants466** [comment]
I was trying to use the laptop in tablet mode (2 in 1) but it seems it doesn't disable the keyboard and trackpad. Also the screen doesn't rotate when i rotate the laptop. Is this related to these drivers or it's something to do with the kernel missing some drivers? 

I'm on 6.0 kernel

**Comment by BeardOverflow** [comment]
Sorry, rotate function is not responsible to this kernel module. The purpose of this repo is to replicate the features of Dragon Center application on Linux.
